# Generated by Django 5.1.7 on 2025-04-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=255)),
                ('product_id', models.IntegerField()),
                ('size_id', models.IntegerField()),
                ('quantity', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('ordered', 'Ordered'), ('pending', 'Pending'), ('inprocess', 'Inprocess')], default='pending', max_length=20)),
                ('creation_dt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tab_cart',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('status', models.SmallIntegerField()),
                ('created_on', models.DateField()),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('describ', models.TextField(blank=True, default='No description available')),
                ('since', models.IntegerField(blank=True, default=2025, null=True)),
                ('image', models.CharField(max_length=200)),
                ('status', models.IntegerField()),
                ('creation_date', models.DateField()),
            ],
            options={
                'db_table': 'tab_brand',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=100)),
                ('parent_cat', models.IntegerField(blank=True, null=True)),
                ('sub_cat', models.IntegerField(blank=True, null=True)),
                ('image', models.CharField(max_length=200)),
                ('status', models.IntegerField()),
                ('describ', models.TextField(blank=True, default='No description available')),
                ('creation_date', models.DateField()),
            ],
            options={
                'db_table': 'tab_category',
            },
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('offer_code', models.CharField(default='AddXYZ', max_length=100)),
                ('describ', models.TextField(blank=True, default='No description available')),
                ('start_date', models.DateField()),
                ('discount', models.IntegerField(default=0)),
                ('end_date', models.DateField()),
                ('image', models.CharField(max_length=200)),
                ('status', models.IntegerField()),
                ('creation_date', models.DateField()),
            ],
            options={
                'db_table': 'tab_offers',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=255)),
                ('order_date', models.DateField()),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('inprocess', 'In Process')], default='pending', max_length=20)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('delivery_partner_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tab_order',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.BigIntegerField()),
                ('product_id', models.IntegerField()),
                ('size_id', models.IntegerField()),
                ('offer_id', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('creation_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tab_order_item',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=500)),
                ('customer_id', models.CharField(max_length=500)),
                ('payment_mode', models.CharField(max_length=500)),
                ('amount', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=500)),
                ('creation_date', models.DateField()),
            ],
            options={
                'db_table': 'tab_payment',
            },
        ),
        migrations.CreateModel(
            name='Product_images',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_id', models.IntegerField(blank=True)),
                ('size', models.CharField(default='xs', max_length=100)),
                ('image_type', models.CharField(default='jpeg', max_length=100)),
                ('path', models.TextField(blank=True)),
                ('status', models.IntegerField()),
                ('creation_date', models.DateField()),
            ],
            options={
                'db_table': 'tab_product_images',
            },
        ),
        migrations.CreateModel(
            name='Product_sizes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_id', models.IntegerField(blank=True)),
                ('size', models.CharField(default='xs', max_length=50)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('describ', models.TextField(blank=True, default='No description available')),
                ('status', models.IntegerField()),
                ('creation_date', models.DateField()),
            ],
            options={
                'db_table': 'tab_product_size',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_name', models.CharField(max_length=100)),
                ('brand', models.IntegerField(blank=True, null=True)),
                ('parent_cat', models.IntegerField(blank=True, null=True)),
                ('sub_cat', models.IntegerField(blank=True, null=True)),
                ('sub_sub_cat', models.IntegerField(blank=True, null=True)),
                ('image', models.CharField(max_length=200)),
                ('status', models.IntegerField()),
                ('describ', models.TextField(blank=True, default='No description available')),
                ('creation_date', models.DateField()),
            ],
            options={
                'db_table': 'tab_products',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('order_id', models.IntegerField(null=True)),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('customer_id', models.EmailField(max_length=254)),
                ('note', models.TextField(blank=True, null=True)),
                ('payment_id', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Shipped'), (2, 'Delivered')], default=0)),
                ('creation_date', models.DateTimeField()),
                ('mob_num', models.CharField(max_length=20)),
                ('town', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tab_shipment',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('status', models.SmallIntegerField()),
                ('created_on', models.DateField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
